### ISSUE TITLE
Help!  What caused the leader election lost?

### ISSUE THREAD

**Issue by AllenZMC** [operator-framework/operator-sdk#1813]
**What did you do?**
 I use `Leader-with-lease` in my operator code. 

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
leader election lost” will appear every other time.
```
2019-08-12T03:05:56.866Z	ERROR	cmd	Manager exited non-zero	{"error": "leader election lost"}
github.com/go-logr/zapr.(*zapLogger).Error
	redis-operator/vendor/github.com/go-logr/zapr/zapr.go:128
main.main
	redis-operator/cmd/manager/main.go:174
runtime.main
```

**Environment**
* operator-sdk version: 0.9.1  

  insert release or Git SHA here: master

* Kubernetes version information: v.1.12

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by joelanford** [comment]
@AllenZMC based on that error message, it sounds like you're using the leader election built into the controller-runtime `Manager`. Is that correct? If so, [here](https://github.com/kubernetes-sigs/controller-runtime/blob/9942957ae4685d7a5330a946379add68ccdf470f/pkg/manager/internal.go#L363) is where that error is coming from.

Are you attempting to run multiple replicas of your operator? It sounds like another instance is getting the leader lock and the instance with this log is losing that election.

**Comment by AllenZMC** [comment]
@joelanford , Yes. I am using the leader election built into the controller-runtime `Manager`.
I only run one replica of my operator. I will continue to pay attention to it.

**Comment by joelanford** [comment]
@AllenZMC Sounds good. Yeah my guess is that you have a rogue replica running somewhere. Maybe an old in-cluster replica that didn't get cleaned up or something running in another terminal or in the background locally with `up local`? 

If you're sure you're only running one replica and you keep seeing this, and it _does_ turn out to be a bug, let us know and we'll help you out with an issue or PR upstream in controller-runtime.

**Comment by AllenZMC** [comment]
I guess the reason is that `LeaseDuration` or `RenewDeadline ` is too short. @joelanford

**Comment by joelanford** [comment]
@AllenZMC I'm not sure. I'm definitely not an expert on controller-runtime's leader election internals, but I don't think a single replica should ever lose an election, which seems to be the case here.

**Comment by AllenZMC** [comment]
@joelanford  Thanks, I think I have found the problem.

**Comment by jessehu** [comment]
Hi @AllenZMC , what's the root cause please?

**Comment by wlmvp** [comment]
Hi @AllenZMC , what's the root cause please?

**Comment by snorwin** [comment]
Hi @AllenZMC  , what's the root cause please?

**Comment by snorwin** [comment]
Since we migrated to operator-sdk 1.0.0, there have been many container restarts caused by the `leader election lost` error. We use a single replica of an operator on openshift v3.11.170 and kubernetes v1.11.0+d4cacc0.

The issue has been resolved by increasing the 'LeaseDuration' to '30s' and the 'RenewDeadline' to '20s'.

**Comment by AllenZMC** [comment]
yes @snorwin

**Comment by Bryce-huang** [comment]
> Since we migrated to operator-sdk 1.0.0, there have been many container restarts caused by the `leader election lost` error. We use a single replica of an operator on openshift v3.11.170 and kubernetes v1.11.0+d4cacc0.
> 
> The issue has been resolved by increasing the `LeaseDuration` to `30s` and the `RenewDeadline` to `20s`.

It just slowed down the frequency and did not solve the problem
