### ISSUE TITLE
Horizontal Pod Auto scaling is not working properly with the Operators when we provide a replica count in the CR

### ISSUE THREAD

**Issue by tabishathar** [operator-framework/operator-sdk#3367]
We are using OCP v4.4, operator sdk v16.0. Deployement apiVersion: apps/v1 and HPA apiVersion: autoscaling/v2beta1.
So using HPA, we are autoscaling the Deployment on CPU load with a targetAverageUtilization: 80.

We have also added a variable in the CR file for the Replica size(which is in Deployment) which is initially 1.

Now, when the CPU utilization is going above 80%, HPA creates new pod as the Desired replica size becomes 2.
As the operator is continuously reconciling, it finds out that that Initial replica size in the CR file as well as the Deployment is 1, so it changes the desired replica size again to 1, terminating the newly created pod.

Now HPA detects only 1 replica and changes the Desired replica count to 2 again, and creates a new pod.
Again operator changes the replica to 1 termination the newly created pod.

This process of Creating and termination of pods goes on continuously in an infinite loop.

Is there any way we can implement and fix this?

**Comment by camilamacedo86** [comment]
Hi @tabishathar, 

After reading your explanation is not clear for me if you are trying to scale the operator pod (E.g `pod/memcached-operator-56f54d84bf-zrtfv` ) or the pod that is created by the operator when you apply the CR (E.g `pod/example-memcached-7c4df9b7b4-lzd6j ). Could you please clarify?

**Comment by tabishathar** [comment]
Hi @camilamacedo86,

We are working with Ansible Operators. Operator pods are working fine, our operator is deploying many Kubernetes objects like deployments and HPA. So, the HPA is scaling the deployments of particular App Pod based on CPU loads. So, when the CPU increases in the Pod for that particular app, it scales the deployment and creates a new pod. And as we have given the initial value for Replica size as 1 , operator is terminating the newly created pods to match the count of replicas in CR file.

**Comment by camilamacedo86** [comment]
I believe that is the expected behaviour. See that the operator will ensure that you have the number of replicas specified in the CR. @fabianvf @asmacdo wdyt?

**Comment by tabishathar** [comment]
@camilamacedo86 Yes, that should be the expected behavior, but because of this behavior of Operators, Autoscaling is not working properly as the pod are continuously restarting and creating. Is there any way we can make Autoscaling work using Ansible base Operators?

**Comment by tengqm** [comment]
It sounds to me like your pods now have two "managers": one is the HPA controller, the other is the Ansible Operator. You have to break one of the management relationship for the other to work. Since you care about auotscaling (which is beyond the Ansible Operator's capability, I guess), you may want your Ansible operator to stop watching your Pods.

**Comment by joelanford** [comment]
@tengqm is correct. You have two controllers fighting over the same field. To allow the HPA to control the replicas, you should remove the handling of that field from your operator and allow that field to be defaulted when the operator initially creates the deployment.

This question has come up before, so we should document the general problem and solution, with this HPA example.

**Comment by tabishathar** [comment]
Thanks guys for your inputs. We were able to resolve this issue by writing a script in ansible roles to manage HPA along with the operators.

**Comment by joshshn** [comment]
@tabishathar can you provide some information on how the script handles to manage hpa with operators? This would be helpful to others like me who are facing similar issue. Thanks.

@joelanford +1 .As you suggest documenting the general problem and soluction would be helpful to operator developers.

**Comment by subrnath** [comment]
We got the similar issue and we fixed it by retrieving the desired replica count from the HPA and use the same in the statefulset if it's greater than var defined in CR file for the replica size.

I am pasting it below -

- name: Get the app hpa object
  k8s_facts:
    api_version: v2beta2
    kind: HorizontalPodAutoscaler
    namespace: '{{ meta.namespace }}'
    name: app
  register: app_hpa

#- debug:
#   var: app_hpa

- name: Get the desiredReplicas count of app_hpa
  set_fact:
    app_current_replica: "{{ app_hpa | json_query(query) }}"
  vars:
    query: 'resources[].{replica: status.desiredReplicas}'

#- debug:
#    var: app_current_replica

- debug:
    var: app_current_replica[0].replica

# tasks file for app
- name: start ams
  k8s:
    state: present
    definition: "{{ lookup('template', 'statefulset-app.j2') | from_yaml  }}"
    namespace: "{{ meta.namespace }}"

---------------------------------------------

Inside the statefulset-app.j2, 

{% if app_current_replica is defined and ( ( app_current_replica[0].replica | int ) > global.scale.app.min_replicas ) %}
  replicas: {{ app_current_replica[0].replica | int }}
{% else %}
  replicas: {{ replicas }}                  ========> Here this replicas is defined in the CR spec file.
{% endif %}

**Comment by santoshborse** [comment]
@subrnath thank you for the example, however it is still not very clear on the objective, what resource HPA is watching? So you want stateful setup to be created ( or updated?) with replica count from HPA and if HPA not exists then from CR?

**Comment by subrnath** [comment]
@santoshborse  HPA is its own definition  as given below where it monitors the cpu/memory utilization of the Pods through metric-server / prometheus and based on that it's doing the scale out/scale in of the pods.

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: amms
spec:
  maxReplicas: min_replica 
  minReplicas:  max_replica
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: app_hpa
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
Issue came with the Operator, Statefulset initially spawns the number of Pods based on min_replica, when hpa scales out, reconcile method of the CRD, again making it min_replica based on it's definition as it's not aware of the current Pod count as decided by HPA.  So the fix is done like that, if there is HPA for this statefulset, get the current "desiredReplicas" field from the HPA. If it's greater than min_replica, use that value in the statefulset task else use the min_replica.

**Comment by nataraj24** [comment]
I know this issue is closed.  I thought this will benefit other members.  We had similar problem and we have overcome the problem of operator reverting the application pod replica count.   Along with above solution mention in this thread we can also use this.  For this problem we need to remove "replicas: " attribute from definition of deployment / statefulset.  When the manifest get applied it will bring a single pod as its default value for "replicas:" attribute.  Post this operator will honor HPA values for replica count.  This is also mentioned in [k8s HPA documentation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling).
