### ISSUE TITLE
Quickstart for Helm-based Operators is not working on OpenShift

### ISSUE THREAD

**Issue by nmasse-itix** [operator-framework/operator-sdk#3767]
## Bug Report

**What did you do?**
I followed https://master.sdk.operatorframework.io/docs/building-operators/helm/quickstart/

```
mkdir nginx-operator
cd nginx-operator
operator-sdk init --plugins=helm
operator-sdk create api --group demo --version v1 --kind Nginx
make docker-build docker-push IMG=docker.io/nmasse/nginx-operator:test
make install
make deploy IMG=docker.io/nmasse/nginx-operator:test
kubectl apply -f config/samples/demo_v1_nginx.yaml
kubectl get all -l "app.kubernetes.io/instance=nginx-sample"
```

**What did you expect to see?**

I expected to see an nginx pod come up. But it never came up.

**What did you see instead? Under which circumstances?**

The operator logs exhibit an error `failed to install release: serviceaccounts \"nginx-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on`

Full log file:

```
{"level":"info","ts":1597936277.6508987,"logger":"cmd","msg":"Version","Go Version":"go1.13.15","GOOS":"linux","GOARCH":"amd64","helm-operator":"v1.0.0"}
{"level":"info","ts":1597936277.6517258,"logger":"cmd","msg":"WATCH_NAMESPACE environment variable not set. Watching all namespaces.","Namespace":""}
{"level":"info","ts":1597936281.6490111,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"127.0.0.1:8080"}
{"level":"info","ts":1597936281.6504083,"logger":"helm.controller","msg":"Watching resource","apiVersion":"demo.my.domain/v1","kind":"Nginx","namespace":"","reconcilePeriod":"1m0s"}
I0820 15:11:21.651919       1 leaderelection.go:242] attempting to acquire leader lease  nginx-operator-system/nginx-operator...
{"level":"info","ts":1597936281.7339883,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I0820 15:11:39.625672       1 leaderelection.go:252] successfully acquired lease nginx-operator-system/nginx-operator
{"level":"info","ts":1597936299.6272435,"logger":"controller","msg":"Starting EventSource","controller":"nginx-controller","source":"kind source: demo.my.domain/v1, Kind=Nginx"}
{"level":"info","ts":1597936299.7290106,"logger":"controller","msg":"Starting Controller","controller":"nginx-controller"}
{"level":"info","ts":1597936299.7297232,"logger":"controller","msg":"Starting workers","controller":"nginx-controller","worker count":4}
{"level":"error","ts":1597936394.6697314,"logger":"helm.controller","msg":"Release failed","namespace":"nginx-operator","name":"nginx-sample","apiVersion":"demo.my.domain/v1","kind":"Nginx","release":"nginx-sample","error":"failed to install release: serviceaccounts \"nginx-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/operator-framework/operator-sdk/internal/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/internal/helm/controller/reconcile.go:181\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
{"level":"error","ts":1597936394.6907682,"logger":"controller","msg":"Reconciler error","controller":"nginx-controller","name":"nginx-sample","namespace":"nginx-operator","error":"failed to install release: serviceaccounts \"nginx-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
```

**Environment**
* operator-sdk version:

```
operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"
helm-operator version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.13.11 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"
```

* Kubernetes version information:

I'm using OpenShift Version 4.3.5, which is based on Kubernetes v1.16.2. 
I'm the cluster-admin of this cluster.

* Kubernetes cluster kind: 3 masters, 3 workers, in VM. 

* Are you writing your operator in ansible, helm, or go?

Helm

**Possible Solution**

The generated `config/rbac/role.yaml` is missing privileges on `nginxes/finalizers`. 
The `operator-sdk create api` command that generates this file needs to be updated to include this privilege since it is required on OpenShift. 

```yaml
##
## Rules for demo.my.domain/v1, Kind: Nginx
##
- apiGroups:
  - demo.my.domain
  resources:
  - nginxes
  - nginxes/status
  - nginxes/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```

Since the generated objects include a `ownerReference` field that references the created CR, on OpenShift the operator needs to be able to set finalizers on the created CR. 

```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-sample
    meta.helm.sh/release-namespace: nginx-operator
  creationTimestamp: "2020-08-20T15:19:08Z"
  labels:
    app.kubernetes.io/instance: nginx-sample
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: nginx-0.1.0
  name: nginx-sample
  namespace: nginx-operator
  ownerReferences:
  - apiVersion: demo.my.domain/v1
    blockOwnerDeletion: true
    controller: true
    kind: Nginx
    name: nginx-sample
    uid: c5d7e996-013f-40ca-bd19-14ba73728eaf
  resourceVersion: "150618365"
  selfLink: /api/v1/namespaces/nginx-operator/serviceaccounts/nginx-sample
  uid: ce916607-58dd-4c1f-bf1e-dbf6f6e86c04
secrets:
- name: nginx-sample-token-99vgm
- name: nginx-sample-dockercfg-rrzb7
```

**Comment by camilamacedo86** [comment]
Hi @nmasse-itix, 

To follow up the tutorial and quickstart you need to have cluster-admin permissions. The tool scaffold  k8s manifests by default which requires this permission. You can change the scope of your project as described in my comment https://github.com/operator-framework/operator-sdk/issues/3733#issuecomment-676550898.

**Comment by nmasse-itix** [comment]
Hi @camilamacedo86 !

Thanks for jumping in and helping me. 

I re-did the whole tutorial (after proper cleanup of course) and I do confirm that:

1. **I am cluster-admin, and connected to the cluster** when doing the `operator-sdk create api` that scaffolds k8s manifests.

```
$ oc whoami
nmasse@redhat.com

$ oc describe clusterrolebinding nmasse@redhat.com-cluster-admin 
Name:         nmasse@redhat.com-cluster-admin
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  cluster-admin
Subjects:
  Kind  Name               Namespace
  ----  ----               ---------
  User  nmasse@redhat.com  

$ operator-sdk create api --group demo --version v1 --kind Nginx
Created helm-charts/nginx
Generating RBAC rules
WARN[0004] The RBAC rules generated in config/rbac/role.yaml are based on the chart's default manifest. Some rules may be missing for resources that are only enabled with custom values, and some existing rules may be overly broad. Double check the rules generated in config/rbac/role.yaml to ensure they meet the operator's permission requirements. 
```

2. When doing so (`operator-sdk create api` while being connected as cluster-admin), the generated `role.yaml` **does NOT contain** `nginxes/finalizers`. 

3. The generated operator fails with **the same error** as before.

So, I followed step-by-step the tutorial, **while being cluster-admin** and the described steps lead to a non-working operator.

Can we fix the `operator-sdk create api` command to generate/scaffold correctly the proper RBAC permissions ?

**Comment by lbroudoux** [comment]
Hi @camilamacedo86 and @nmasse-itix 

I've re-run all the tests from scratch on both Minikube and OpenShift and comes to the conclusion that Nicolas suggestion is mandatory for OpenShift.

## On Minikube

On a fresh install, apply the following commands:
```
mkdir nginx-operator
cd nginx-operator
operator-sdk init --plugins=helm --domain=com --group=example --version=v1alpha1 --kind=Nginx
export IMG=quay.io/lbroudoux/nginx-operator:v0.0.1
make docker-build docker-push IMG=$IMG
make deploy IMG=$IMG
kubectl apply -f config/samples/example_v1alpha1_nginx.yaml -n nginx-operator-system
```

Operator deploys correctly and is able to deploy the `nginx-sample` custom resource. Everything is running fine.

Checking the logs:
```
$ kubectl logs deployment.apps/nginx-operator-controller-manager  -n nginx-operator-system -c manager | grep error
[EMPTY]
```

Clean-up everything
```
make undeploy
cd .. && rm -rf nginx-operator
```

## On OpenShift

On a fresh 4.5 cluster, apply the same following commands:
```
mkdir nginx-operator
cd nginx-operator
operator-sdk init --plugins=helm --domain=com --group=example --version=v1alpha1 --kind=Nginx
export IMG=quay.io/lbroudoux/nginx-operator:v0.0.1
make docker-build docker-push IMG=$IMG
make deploy IMG=$IMG
kubectl apply -f config/samples/example_v1alpha1_nginx.yaml -n nginx-operator-system
```

Operator deploys correctly but is **not able** to deploy the `nginx-sample` custom resource. 

Checking the logs:
```
$ kubectl logs deployment.apps/nginx-operator-controller-manager  -n nginx-operator-system -c manager | grep error
{"level":"error","ts":1598273662.1000674,"logger":"helm.controller","msg":"Release failed","namespace":"nginx-operator-system","name":"nginx-sample","apiVersion":"example.com/v1alpha1","kind":"Nginx","release":"nginx-sample","error":"failed to install release: serviceaccounts \"nginx-sample\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/operator-framework/operator-sdk/internal/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/internal/helm/controller/reconcile.go:181\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
```

Clean-up everything
```
make undeploy
cd .. && rm -rf nginx-operator
```

## On OpenShift with modified RBAC on finalizers

On a fresh 4.5 cluster, apply the same following commands:
```
mkdir nginx-operator
cd nginx-operator
operator-sdk init --plugins=helm --domain=com --group=example --version=v1alpha1 --kind=Nginx
export IMG=quay.io/lbroudoux/nginx-operator:v0.0.1
```

before pursuing, edit `config/rbac/role.yaml` and add the `nginxes/finalizers` resource like below:
```
[...]
##
## Rules for example.com/v1alpha1, Kind: Nginx
##
- apiGroups:
  - example.com
  resources:
  - nginxes
  - nginxes/status
  - nginxes/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

# +kubebuilder:scaffold:rules
```

Finish with the last commands:
```
make docker-build docker-push IMG=$IMG
make deploy IMG=$IMG
kubectl apply -f config/samples/example_v1alpha1_nginx.yaml -n nginx-operator-system
```

Operator deploys correctly and is able to deploy the `nginx-sample` custom resource.

Checking the logs:
```
$ kubectl logs deployment.apps/nginx-operator-controller-manager  -n nginx-operator-system -c manager | grep error
EMPTY
```

There's a remaining issue when deploying the Pod because of security conflict with OpenShift SCC but it's not related to Operator SDK:
```
2020/08/24 13:13:19 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2020/08/24 13:13:19 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```

## Conclusion

As a conclusion, I would say that the tests confirm that Operator SDK for Helm does not work out-of-the-box on OpenShift. Finalizer permission on Custom Resource is required by OpenShift because of more restrictive default RBAC permissions on serviceaccount that should not be there on upstream Kubernetes. As this permission is not required by custom code logic and Operator SDK should be the preferred way for customers to develop operators on Red Hat's OpenShift, I suggest adding this permission by default when generating scaffold resources for a new Helm backed API.

**Comment by camilamacedo86** [comment]
Hi @lbroudoux 
really thank you for your comment;

So, it means that we need to: 
- 1) update the docs as described in; https://github.com/operator-framework/operator-sdk/issues/3733#issuecomment-676521753
- 2) improve the tool to generated for Ansible/Helm the status and finalizers roles by default. (I assume that the same issue will also be checked with Ansible i) E.g

```ymal
[...]
##
## Rules for example.com/v1alpha1, Kind: Nginx
##
- apiGroups:
  - example.com
  resources:
  - nginxes
  - nginxes/status
  - nginxes/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"

# +kubebuilder:scaffold:rules
```

**Comment by lbroudoux** [comment]
I've made some tests with Ansible but the permission is not required as the SDK does not place a finalizer on the Custom Resource. This seems to be done only with Helm.

**Comment by joelanford** [comment]
> update the docs as described in; #3733 (comment)

@camilamacedo86 These docs are not related to this issue AFAICT. The operator _developer_ needs cluster admin to be able to create the CRDs and deploy the operator into the cluster. The `operator` does NOT need cluster admin (it uses the Role defined in `config/rbac/role.yaml`)

I think the solution here is just the simple addition of the finalizers permission in the default Helm role scaffold here: https://github.com/operator-framework/operator-sdk/blob/35df158954e7dbc643bf705e5710112dcdc5f005/internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go#L159-L161

@lbroudoux or @nmasse-itix Would either of you be interested in submitting a PR to fix this issue?

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

> @camilamacedo86 These docs are not related to this issue AFAICT. The operator developer needs cluster admin to be able to create the CRDs and deploy the operator into the cluster.

The helm quickstart has not the pre-requirement for the users know the user requires cluster-admin permission. 

See: https://github.com/operator-framework/operator-sdk/issues/3733#issuecomment-676521753

- Ensure that all quickstart and tutorial docs for Ansible/Helm/GO has as Prerequisites `User authorized with cluster-admin permissions`
- Also, would be very nice we have a doc on the website with quite similar info of https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#iam-rolebinding-bootstrap to link on the Prerequisites. We cannot link the cloud.google.com doc, however, it is exactly the info that shows missing.  

The issue #3733 is the same scenario faced here.

**Comment by camilamacedo86** [comment]
Done PR: https://github.com/operator-framework/operator-sdk/pull/3779

**Comment by joelanford** [comment]
Re-opening because PR #3779 did not resolve this issue for Helm operators. It applied the change to the Ansible operator scaffolding, but this permission change is not required for Ansible operators because the Ansible operator does not use a finalizer on the main CR.

I will submit a PR shortly that makes this change for Helm and reverts the change for Ansible.

**Comment by camilamacedo86** [comment]
For Helm, the finalizer permission will be added in #4105
For Ansible, the finalizer permission was added in #3779

Also, we need to cherry-pick the #4105 to 1.0.
