### ISSUE TITLE
scorecard - produce a better error response when RBAC errors occur inside kuttl

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/operator-sdk#4096]
## Feature Request

when a user doesn't provide all the necessary RBAC privs to their service account, when
running a kuttl test, kuttl will fail with RBAC errors.  This causes scorecard to produce
and empty result "{}" which is hard to debug.  And users will almost certainly not get
their RBAC privs correct all the time or will forget to specify the --service-account
CLI flag to scorecard.

#### Describe the solution you'd like.

There is a wrapper bash script that invokes kuttl within the scorecard-test-kuttl image, that
script should detect a kuttl error, and if found, produce scorecard compatible output
so that scorecard can return some sort of human readable error back to the end user.

**Comment by kensipe** [comment]
The issue was resolved upstream in kuttl.  Kuttl did NOT create a report for a `--report` if no testcases were run or if there was a startup failure (for instance auth issue or bad connection).  This was fixed in KUTTL and is available with `0.7.1` release.  It will now always create a report if requested and it will provide failure info if an infra tooling failure occurs.

My understanding was a change in the base image which @jmccormick2001 needs for scorecard and he is looking into it.

**Comment by estroz** [comment]
Closed by #4138

**Comment by jmccormick2001** [comment]
still a problem here I think, needs to be confirmed that the bump fixed it.

**Comment by estroz** [comment]
Output from a manual test (created using the [Go sample](https://github.com/operator-framework/operator-sdk/tree/v1.1.0/testdata/go/memcached-operator) with [default kuttl config and assert](https://sdk.operatorframework.io/docs/advanced-topics/scorecard/kuttl-tests/)):
```console
$ kind create cluster --node-image=kindest/node:v1.18.2
$ pushd ${GOPATH}/src/github.com/operator-framework/operator-sdk
$ make image/scorecard-test-kuttl && kind load docker-image quay.io/operator-framework/scorecard-test-kuttl:dev
$ popd
$ operator-sdk scorecard ./bundle --selector=suite=kuttl --skip-cleanup=true
--------------------------------------------------------------------------------
Image:      quay.io/operator-framework/scorecard-test-kuttl:dev
Labels:
	"suite":"kuttl"
	"test":"assert"
Results:
	Name: list-pods
	State: fail

	Errors:
		pods "pod-1" is forbidden: User "system:serviceaccount:default:default" cannot get resource "pods" in API group "" in the namespace "default"
```

So this is fixed. Closing.
