### ISSUE TITLE
Create a new Issue template for Documentation issues

### ISSUE THREAD

**Issue by NissesSenap** [operator-framework/operator-sdk#4129]
## Add Issue tempalte for docs issues
edit (asmacdo):
There are now buttons for creating issues from each page of the docs so this is mostly done. The only remaining work is to add a Issue template [here](https://github.com/operator-framework/operator-sdk/tree/master/.github/ISSUE_TEMPLATE) and update the "edit this page" links to use that template.

## Original Feature Request (outdated)
Make it easier to create issues for sdk.operatorframework.io/docs/

#### Describe the problem you need a feature to resolve.

Recently Red Hat have started to go for easier integration with github for the docs pages, would be great if we can have this for operator framework as well.

The docs page of https://sdk.operatorframework.io/docs/ currently don't have any easy integration with github.
Would love to see something like: https://docs.openshift.com/container-platform/4.6/welcome/index.html where you can push "Open an issue" and it will automiatcally start to fill in a github issue and pointing on the correct page.

#### Describe the solution you'd like.

Change to another hugo theme with support for issues or even PR links created in github through a klick of a button on the docs page.
The major drawback I can see is that you initially get more docs issues but in the long run this should increase the documentation quality.
It will also make it easier to track docs issues since you can automatically tag the issues created from this template + they will follow the same subject line name standard.

**Comment by camilamacedo86** [comment]
HI @NissesSenap, 

It shows nice. +1 for me. Would you like to push a pr with the solution? WDYT?

**Comment by asmacdo** [comment]
Docsy has support for this feature this is from the theme's example:
![Screenshot from 2020-10-30 10-19-43](https://user-images.githubusercontent.com/1028657/97716054-82b2b380-1a99-11eb-89b9-89bf821d4a2c.png)

AFAICT we already hvae this feature enabled, so I'm not sure why it isn't being picked up. @matthewcarleton, this sounds familiar, do you remember anything about this? https://github.com/operator-framework/operator-sdk/blob/master/website/config.toml#L133-L137

**Comment by camilamacedo86** [comment]
You did notice that we have a create project issue already on the website. So, shows that we can close this one since the RFE is addressed already., 

@NissesSenap I am closing it. However, please feel free to ping us to re-open if you think that is required.

**Comment by NissesSenap** [comment]
Hmm I'm not sure what you are talking about @camilamacedo86 I can't see any "project issue" on the website but I'm usually half blind so please point it out to me :)

@asmacdo without knowing the hugo theme that you are using. Doesn't that only trigger when you push some feedback button?
Can't say that I found the feedback button ether but I guess you will be redirected to: https://github.com/operator-framework/operator-sdk/issues/new

Bellow is a picture of what I see from my chrome browser, I looked in firefox and it's the same.

![image](https://user-images.githubusercontent.com/14774899/97724883-caebc900-1acd-11eb-8800-aa28466ca2d9.png)

BTW I love the bottom of the page "Last modified August 27, 2020: fix: use relative path in documentation (#3791) (6917885e)  in the bottom of the page."

**Comment by asmacdo** [comment]
The picture I posted should show up on the right side of the page like it does on the example site. https://example.docsy.dev/docs/

This is still an issue, but it is a dupe of: https://github.com/operator-framework/operator-sdk/issues/3642

**Comment by asmacdo** [comment]
But yes, once it's working, there will be a "File an issue" link that points to https://github.com/operator-framework/operator-sdk/issues/new. 

We could create a new type of issue here: https://github.com/operator-framework/operator-sdk/issues/new/choose

I think that having a "documentation issue" template sounds like a pretty good idea.

Also, I'm reopening this issue and closing #3642 since there is more info here.

**Comment by asmacdo** [comment]
It looks like this one is actually already done and will be included in the next release. See https://master.sdk.operatorframework.io/docs/

**Comment by asmacdo** [comment]
Leaving this open to cover the creation of a new issue template for docs issues:
https://github.com/operator-framework/operator-sdk/issues/new/choose

**Comment by asmacdo** [comment]
This one should be pretty easy for a new contributor, feel free to ping me to get help.

**Comment by hickeyma** [comment]
@asmacdo @camilamacedo86 @NissesSenap I can work on this if thats ok?
