### ISSUE TITLE
enable scorecard to override image pull policy

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/operator-sdk#4423]
## Feature Request

in scorecard today, IfNotpresent is the default pull policy for test images, it would be useful to let users override this within the scorecard config.yaml file to specify for example a pull policy of Always.

https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/testpod.go#L54

#### Describe the solution you'd like.

retain the default perhaps, but allow this value to be overrode within the config.yaml

something like this:
```
kind: Configuration
apiversion: scorecard.operatorframework.io/v1alpha3
metadata:
  name: config
stages:
- tests:
  **- imagePullPolicy:  Always**
  - image: quay.io/operator-framework/tekton-scorecard-image:dev
    entrypoint:
    - tekton-scorecard-tests
    - customtest1
    labels:
      suite: tekton
      test: customtest1

```

**Comment by estroz** [comment]
@jmccormick2001, @theishshah and I think it would be a good idea to switch the default to "Always" to avoid potential bugs if the user is unaware of caching, on top of adding a configurable policy. Thoughts?

/assign @theishshah

**Comment by jmccormick2001** [comment]
one thing to note here, if you have say 10 tests, and an imagePullPolicy of Always, it will mean the test image will get pulled down 10 times as each test Pod is created...so, this default choice might impact runtime, something to be aware of.  As long as the end user can override the default to something other than Always, they can get the effect they want, but its worth noting I think as to the impact of switching to Always as the default.

**Comment by theishshah** [comment]
Addressed by #4762

**Comment by jberkhahn** [comment]
Looks like the PR was merged so I'm gonna close this.

**Comment by estroz** [comment]
This was not actually fixed, see https://github.com/operator-framework/operator-sdk/pull/4762#discussion_r616041362

**Comment by theishshah** [comment]
Blocked by https://github.com/operator-framework/operator-sdk/pull/5191

**Comment by theishshah** [comment]
Pushing this ticket out by 1 release. Needs further discussion as our KIND in CI does not support the ability to drop in "Always" as the pull policy - regardless of busybox/ubi. If we decide we want to ship to users with "Always" a configuration path needs to be built to allow a modified version to be run in CI KIND environments.

**Comment by theishshah** [comment]
PR #5054 was an attempt at the drop-in replacement, I will work on the configuration path model on this branch for those interested.
